"""posts table

Revision ID: 4b356b86b11a
Revises: dd605be63570
Create Date: 2022-07-12 12:05:26.322629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b356b86b11a'
down_revision = 'dd605be63570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=140), nullable=True))
    op.drop_column('post', 'blogpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('blogpost', sa.VARCHAR(length=180), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
