"""empty message

Revision ID: 84b173f8bd94
Revises: 66f7226096e3
Create Date: 2022-07-12 12:16:12.398090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b173f8bd94'
down_revision = '66f7226096e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'blogpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('blogpost', sa.VARCHAR(length=180), nullable=True))
    # ### end Alembic commands ###
